# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'


pool:
  vmImage: 'windows-2019'

steps:
- script: dir
  displayName: "Debug Help"

- powershell: Get-ChildItem -Recurse
  displayName: "Powershell get items"

- powershell: .\Build\Build.ps1
  displayName: "Testing Script"

- powershell: Test-Path ".\Test-Script\NewTestScript.ps1"
  displayName: "Find Script"

- powershell: Write-Host $env:Foo; Write-Host $env:MySecret
  env:
    MySecret: $env:Foo

- powershell: Get-Content .\Build\ReleaseNotes.md
  displayName: "Getting content"

jobs:
- template: .\Build\azure-pipeline-release.yml